stages:
  load:
    cmd: python src/load_data.py data/raw data/processed/combined_data.csv
    deps:
      - src/load_data.py
      - data/raw
    outs:
      - data/processed/combined_data.csv

  preprocess:
    cmd: python src/preprocess.py 
    data/processed/combined_data.csv
    data/processed/filtered_data.csv config.yaml
    deps:
      - src/preprocess.py
      - data/processed/combined_data.csv
      - config.yaml
    outs:
      - data/processed/filtered_data.csv

  find_peaks:
    cmd: python src/peak_analysis.py 
    data/processed/filtered_data.csv 
    data/peaks
    deps:
      - src/peak_analysis.py
      - data/processed/filtered_data.csv
    outs:
      - data/peaks